const Teams = [
  {
    name: "GURU BHARGAVA",
    number: "1",
    teams: [
      {
        teamNumber: 1,
        teamName: "Akrash",
        teamLead: "Akanksha Kabra",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "Innovation catalysts",
        teamLead: "Nimitha Singireddy",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "Developers",
        teamLead: "Banoth Anand",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "01_Coders",
        teamLead: "Gangapurapu Niharika",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "AnsiCode",
        teamLead: "Adityanath",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "Creative catalysts",
        teamLead: "Ravali manthini",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "02_Smart Coderss",
        teamLead: "Samala Keerthi",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "goWeb",
        teamLead: "Srirama Venu",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "Butterflies",
        teamLead: "Madhulika Pabbisetty",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Team 7",
        teamLead: "Anudeep Pannala",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "WEB ELITES",
        teamLead: "Kanuri Bharath Chandra Chowdary",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "Pro coders",
        teamLead: "Kritika Mutagar",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "Webworks",
        teamLead: "Rolla Pavani",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Arctic fox",
        teamLead: "Jyothsya",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "01_Web Wizards",
        teamLead: "T. Krishna Sowmya",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "01_Strawhats",
        teamLead: "Laxman Reddy Vennam",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "02_Trailblazers",
        teamLead: "Ashreen Tabassum",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "One",
        teamLead: "G Aravind Nayak",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },

  {
    name: "SURAJ SANGHANBHATLA",
    number: "2",
    teams: [
      {
        teamNumber: 1,
        teamName: "Heavenly Hackers",
        teamLead: "Bharath Kalyan Muthyala",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 2,
        teamName: "MADMEN",
        teamLead: "Budidha Laxman",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 3,
        teamName: "UnHoly",
        teamLead: "Morampudi Buddu Uday",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 4,
        teamName: "Team strivers",
        teamLead: "Maneeshkumar bonagiri",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 5,
        teamName: "Saviours",
        teamLead: "Gugulothu bhavana",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 6,
        teamName: "02_Kanyarasi",
        teamLead: "Bharath",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 7,
        teamName: "LOGIC OPTIMISERS",
        teamLead: "Vipin Krishna Rangu",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 8,
        teamName: "04_Webwizards",
        teamLead: "Rohith Reddy",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 9,
        teamName: "02_Tech Army",
        teamLead: "Bheemaram Akshaya",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 10,
        teamName: "Byte Bridgers",
        teamLead: "Deepak Srinivas Banda",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 11,
        teamName: "01_Web warriors",
        teamLead: "G.Bhavana Reddy",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 12,
        teamName: "Strikers",
        teamLead: "Korella Aaditya Kumar",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 13,
        teamName: "March",
        teamLead: "Tummala Viswa Prateek",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 14,
        teamName: "01_CodeCrafters",
        teamLead: "Ganta Hepcyba",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 15,
        teamName: "HackMasters",
        teamLead: "Devi Sri Charan Kasoju",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 16,
        teamName: "InnovX",
        teamLead: "K.Sai Srihitha",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 17,
        teamName: "01_Trail Blazers",
        teamLead: "K.Ravalika",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 18,
        teamName: "#hackers",
        teamLead: "Srivarshika Reddy",
        timeSlot1: "3:45 - 4:00",
      },
    ],
  },
  {
    name: "P. ROHITH KUMAR VASISTA",
    number: "3",
    teams: [
      {
        teamNumber: 1,
        teamName: "The Elite",
        teamLead: "Madikuntawar Srikar",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "02_CodeCrafters",
        teamLead: "Satwik Obilineni",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "TechTadpoles",
        teamLead: "Cirolla Atharva Reddy",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "Team GAJALA",
        teamLead: "SASI Kaladhar. G",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "SPAD",
        teamLead: "Spoorthi Mamidi",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "The Squad",
        teamLead: "PRANJAL",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "LJ",
        teamLead: "Ramitha thogari",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "69 coders",
        teamLead: "Pranav deepak",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "IT2024",
        teamLead: "RENUKA POLADI",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Web techies",
        teamLead: "Puli Anvitha Reddy",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "01_Debug Thugs",
        teamLead: "Abhinav Sripada",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "source code",
        teamLead: "Sharath Chandra",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "Loan Wolf Squad",
        teamLead: "Lekhan",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Thunders",
        teamLead: "K HARSHA VARDHAN CHOWDARY",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "Args",
        teamLead: "M. Harshitha",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "Webcrafters",
        teamLead: "Narla Sreeja",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "Error 404",
        teamLead: "Lokesh Sathini",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "Tech invo",
        teamLead: "G AASHISH",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },
  {
    name: "G. DHANUSH",
    number: "4",
    teams: [
      {
        teamNumber: 1,
        teamName: "Ecllipse Hakers",
        teamLead: "Karthikeya Ananthula",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "Team dev",
        teamLead: "BATTHULA VIJAYA VENKATA RAMARAJU",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "TechTerminators",
        teamLead: "JSV Suraj",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "05_WEBWIZARDS",
        teamLead: "ANISH BHARGAV REDDY CHALLA",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "SPArK",
        teamLead: "Sanjana Chenna",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "02_Hustlers",
        teamLead: "Shaik arham raza",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "Team Titans",
        teamLead: "Vadla Surya Teja",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "01_Hackers",
        teamLead: "Yashwanth Katragadda",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "Unstoppable",
        teamLead: "V. Sanjana",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Team Fusion",
        teamLead: "Komirishetty Saketh",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "Space Cadets",
        teamLead: "Abhishek Allaboina",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "Solution sprinters",
        teamLead: "Gannoju Sahasra",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "Flawless4",
        teamLead: "Kaja Aakash",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Skilled Vision Masters Squad",
        teamLead: "Sushanth Samala",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "The Innovation Incubators",
        teamLead: "Vaddepalli Bhavana",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "snpp",
        teamLead: "Jaksani Prabhas",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "TEAM ASCII",
        teamLead: "Jangam Pranav",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "Sankalp",
        teamLead: "Bharathdwaja Sree Vaishnavi",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },
  {
    name: "RITISH REDDY",
    number: "5",
    teams: [
      {
        teamNumber: 1,
        teamName: "TEAM DIJKSTRA",
        teamLead: "Annabathula Pavan Kumar",
        timeSlot1: "10:15 - 10:30",
      },

      {
        teamNumber: 2,
        teamName: "01_Dark Code",
        teamLead: "K.Anil Kumar",
        timeSlot1: "10:30 - 10:45",
      },

      {
        teamNumber: 3,
        teamName: "Team Kadane",
        teamLead: "Sathvik Kunuru",
        timeSlot1: "10:45 - 11:00",
      },

      {
        teamNumber: 4,
        teamName: "Brute Force",
        teamLead: "Md Karimunnisa",
        timeSlot1: "11:00 - 11:15",
      },

      {
        teamNumber: 5,
        teamName: "Coding Shinobis",
        teamLead: "Ajay viswas",
        timeSlot1: "11:15 - 11:30",
      },

      {
        teamNumber: 6,
        teamName: "ANK",
        teamLead: "Shabad Nitin",
        timeSlot1: "11:30 - 11:45",
      },

      {
        teamNumber: 7,
        teamName: "WrongAnswer",
        teamLead: "V.Vidhyadhar Reddy",
        timeSlot1: "11:45 - 12:00",
      },

      {
        teamNumber: 8,
        teamName: "02_Dark Coders",
        teamLead: "Manasa Virivinti",
        timeSlot1: "12:00 - 12:15",
      },

      {
        teamNumber: 9,
        teamName: "SARK",
        teamLead: "Suraksha Dusa",
        timeSlot1: "12:15 - 12:30",
      },

      {
        teamNumber: 10,
        teamName: "Rockstars",
        teamLead: "M N S Sri Harshini",
        timeSlot1: "12:30 - 12:45",
      },

      {
        teamNumber: 11,
        teamName: "The Tech Sheild",
        teamLead: "Alladi Shiva Vinay",
        timeSlot1: "12:45 - 1:00",
      },

      {
        teamNumber: 12,
        teamName: "Star Techies",
        teamLead: "A Guru Sai Nandan",
        timeSlot1: "2:00 - 2:15",
      },

      {
        teamNumber: 13,
        teamName: "Muffins",
        teamLead: "Rohith Chinthoju",
        timeSlot1: "2:15 - 2:30",
      },

      {
        teamNumber: 14,
        teamName: "01_Alpha z",
        teamLead: "G.nishanth",
        timeSlot1: "2:30 - 2:45",
      },

      {
        teamNumber: 15,
        teamName: "Comp crew",
        teamLead: "Gunti Harini",
        timeSlot1: "2:45 - 3:00",
      },

      {
        teamNumber: 16,
        teamName: "Team hulk",
        teamLead: "Pulluru satwik",
        timeSlot1: "3:00 - 3:15",
      },

      {
        teamNumber: 17,
        teamName: "Avalanche",
        teamLead: "Srilahari Ganta",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "TechTitans",
        teamLead: "Thanmayee T",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },
  {
    name: "KARRE HANISH",
    number: "6",
    teams: [
      {
        teamNumber: 1,
        teamName: "DreamTeam",
        teamLead: "Akula Sharath",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "Kernel",
        teamLead: "Dhanush Douda",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "Tech Bots",
        teamLead: "N.Kavya Reddy",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "Web ninjas",
        teamLead: "Nyalakanti Vaishnavi",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "Tech Connect",
        teamLead: "Adla Sai Karthik",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "SkyHigh",
        teamLead: "Vikranth",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "SPD",
        teamLead: "Chinta NVD Prashanth",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "Bits and Bytes",
        teamLead: "Erikireddy Varshitha",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "01_Ctrl Alt Elite",
        teamLead: "SUHRUTHA IMADABATHUNI",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Team Developers",
        teamLead: "Konda Saikrishna",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "02_Web Wizards",
        teamLead: "Puvvala Jogeeswara Venkata Naga Sai",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "The Deciders",
        teamLead: "Valgiri Sri Varsha",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "01_Tech Army",
        teamLead: "Gadila Durga Prasad",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Error 999+",
        teamLead: "Katepally Varshitha",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "Enthusiastic Techies",
        teamLead: "Radha Madhavi Pendyala",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "03_CodeCrafters",
        teamLead: "Sabbasani Ashok Kumar Reddy",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "Data Demons",
        teamLead: "Rainy Sandilya",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "01_Akatsuki",
        teamLead: "Shashank Kathuroju",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },

  {
    name: "K. NAGA SAI NITHIN",
    number: "7",
    teams: [
      {
        teamNumber: 1,
        teamName: "Team strikers",
        teamLead: "Shaik Rizwana",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "06_WebWizards",
        teamLead: "Bhattu Akhil Teja",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "Striver",
        teamLead: "Mohammad Aseem",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "Web Centric",
        teamLead: "Rvssm Sandeep",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "Gamma",
        teamLead: "Bhanu Prakash Patlori",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "Code army",
        teamLead: "Ciripuram varshith",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "03_Tech Army",
        teamLead: "GONNABATTULA SANDEEP",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "FusionFive",
        teamLead: "Rishitha Akula",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "Block Miners",
        teamLead: "Thummakunta Trishank",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Byte Bandits",
        teamLead: "Ippa Abhijith",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "Shouryanga parvam",
        teamLead: "Upasana",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "Script Wizards",
        teamLead: "Mamindla Manish Reddy",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "Webgenious",
        teamLead: "Sathwik Tammishetti",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Fabulous5",
        teamLead: "Adepu Yashaswini",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "Five star",
        teamLead: "Bhargavi Upadhyay",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "Last Benchers anta",
        teamLead: "V Chandana",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "Team Knights",
        teamLead: "Kaveti Sai Sumedh",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "LOVE ALL",
        teamLead: "Kamal Kumar Kolisetty",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },

  {
    name: "N. PARTHAV",
    number: "8",
    teams: [
      {
        teamNumber: 1,
        teamName: "Qliphoth",
        teamLead: "Thonda Rishith",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "Chanakya",
        teamLead: "Vishwanatham Manvith",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "Whizz kids",
        teamLead: "Aishwarya",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "Nitin P",
        teamLead: "P. Nitin",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "Recession warriors",
        teamLead: "Peddireddy srijith",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "abcd123",
        teamLead: "Pranav Gaddi",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "WASMBois",
        teamLead: "Yaddanapudi Vishnu Srivatsava",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "TechSpark",
        teamLead: "Bandapalli Maithili",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "Twelve",
        teamLead: "Kaja Yasaswini",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Code Commandos",
        teamLead: "Abhinav Kesamsetty",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "01_Tech titans",
        teamLead: "Chaitanya Reddy",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "02_Innovators",
        teamLead: "Hasini Vuppu",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "Raising birds.",
        teamLead: "Lasya seedarala",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Team Demons",
        teamLead: "Douda Shalini",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "Slayers",
        teamLead: "M.Rachana",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "02_Web Warriors",
        teamLead: "M.N.V ANIRUDH",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "01_Pheonix",
        teamLead: "A.Sreenidhi",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "Team React",
        teamLead: "B Shiva Teja",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },
  {
    name: "M. KRISHNA PRIYA",
    number: "9",
    teams: [
      {
        teamNumber: 1,
        teamName: "02_Ctrl Alt Elite",
        teamLead: "P. Uma Maheswar Reddy",
        timeSlot1: "10:15 - 10:30",
      },
      {
        teamNumber: 2,
        teamName: "Limit Breakers",
        teamLead: "Kondaveeti Vishesh",
        timeSlot1: "10:30 - 10:45",
      },
      {
        teamNumber: 3,
        teamName: "Decipher",
        teamLead: "Abhigna",
        timeSlot1: "10:45 - 11:00",
      },
      {
        teamNumber: 4,
        teamName: "Teen titans go",
        teamLead: "M rohith",
        timeSlot1: "11:00 - 11:15",
      },
      {
        teamNumber: 5,
        teamName: "Game changers",
        teamLead: "Aashritha Raj Poshaboina",
        timeSlot1: "11:15 - 11:30",
      },
      {
        teamNumber: 6,
        teamName: "Among us",
        teamLead: "Yashwanth Pothala",
        timeSlot1: "11:30 - 11:45",
      },
      {
        teamNumber: 7,
        teamName: "Web Crawlers",
        teamLead: "Salsabil Shehnaz",
        timeSlot1: "11:45 - 12:00",
      },
      {
        teamNumber: 8,
        teamName: "Memory out of bounds",
        teamLead: "AGITHE PRASHANTH",
        timeSlot1: "12:00 - 12:15",
      },
      {
        teamNumber: 9,
        teamName: "WebWeavers",
        teamLead: "A.Sreenidhi",
        timeSlot1: "12:15 - 12:30",
      },
      {
        teamNumber: 10,
        teamName: "Neversettle",
        teamLead: "Ananya Arisenapally",
        timeSlot1: "12:30 - 12:45",
      },
      {
        teamNumber: 11,
        teamName: "Lakshya",
        teamLead: "KUCHARLAPATI ANUSHA",
        timeSlot1: "12:45 - 1:00",
      },
      {
        teamNumber: 12,
        teamName: "Bariant",
        teamLead: "Surya Murala",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 13,
        teamName: "Atlantis",
        teamLead: "SANDA ADHARSH",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 14,
        teamName: "Team X",
        teamLead: "T. Sai Sushanth",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 15,
        teamName: "Catastrophe",
        teamLead: "TALASILA SRI KRISHNA CHAITANYA",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 16,
        teamName: "03_Web Wizards",
        teamLead: "Cheerla Uday Sagar",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 17,
        teamName: "Hack Hive",
        teamLead: "Kaeith Emmanuel Eddu",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 18,
        teamName: "Hive",
        teamLead: "Ravula Amrutha Varshini",
        timeSlot1: "3:30 - 3:45",
      },
    ],
  },
  {
    name: "SAMANIDHAR REDDY GURRAM",
    number: "10",
    teams: [
      {
        teamNumber: 1,
        teamName: "03_WebWarriors",
        teamLead: "Gaddam Gopi Harishitha",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "Console.log",
        teamLead: "Sanjana Kasireddy",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "04_Web warriors",
        teamLead: "KODURU CHANDRAKANTH REDDY",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "Web O than",
        teamLead: "NUMAD",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "#404 Page Not Found",
        teamLead: "P Rakesh Kumar",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "01_Innov8Tech",
        teamLead: "PODILA SRAVYA",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "DevDynamos",
        teamLead: "Thalluri Sai Lokesh",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "TeamFi",
        teamLead: "Battu Sri Manikanta",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "05_Web warriors",
        teamLead: "Reshma Mulpuri",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Coding Titans",
        teamLead: "Paripally Abhishek",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },

  {
    name: "B RISHAB",
    number: "11",
    teams: [
      {
        teamNumber: 1,
        teamName: "Team spirit",
        teamLead: "Tharapatla Harshitha",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "Webers",
        teamLead: "Hemanth. T",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "The Shield",
        teamLead: "Sri Vaishnavi Yadavalli",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "Abstract",
        teamLead: "Abhilash Banda",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "Team 404 not found",
        teamLead: "Kancherla Swathi",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "High Five",
        teamLead: "Kiranmayi",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "01_Kanyaraasi",
        teamLead: "Kuchur Vaibhava Lakshmi",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "Pluto",
        teamLead: "Kunchala Harsha Vardhan",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Black Wolf",
        teamLead: "Mandala Sree Harshini",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Team Seven",
        teamLead: "Rajuri Sriteja",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "B. LIKHITA",
    number: "12",
    teams: [
      {
        teamNumber: 1,
        teamName: "Web Nexus",
        teamLead: "GURUMETKAL BHARATH SIMHA REDDY",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "TEAM NATUGUNTLA",
        teamLead: "HIMANTH MADDIPATI",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "01_Hustlers",
        teamLead: "K Sathwik Reddy",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "01_Byte Busters",
        teamLead: "Kshetragna Adusumilli",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "Gladiators",
        teamLead: "N Harsha Vardhan Reddy",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "Spam bytes",
        teamLead: "R.S.Rithika",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "Spartans",
        teamLead: "Shaik Shaaz Hussain",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "04_CodeCrafters",
        teamLead: "ATTELLI SANJAY KUMAR",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "IT'S",
        teamLead: "B Rohan",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "02_Phoenix",
        teamLead: "Manoj Kumar",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "MANIDEEP GANGISHETTY",
    number: "13",
    teams: [
      {
        teamNumber: 1,
        teamName: "SSM",
        teamLead: "K.Simritha",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "Geek Navi",
        teamLead: "MORISHETTY NIKHIL",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "06_CodeCrusaders",
        teamLead: "Sajja Lakshmi Priya",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "02_InnoVate",
        teamLead: "Himanshu Bhatraj",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "02_Error no 404",
        teamLead: "Yerram Bhanu Teja",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "THE  BOYZ!",
        teamLead: "SERIMALLE TILAK VARDHAN",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "What next?",
        teamLead: "K.Sree Ram Neeraj",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "Work wizards",
        teamLead: "Sree Charan Reddy",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Algorithm Architects",
        teamLead: "M. Spoorthy",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Nirvana",
        teamLead: "Shruthika Sunku",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "ANJAN PRITHVI",
    number: "14",
    teams: [
      {
        teamNumber: 1,
        teamName: "Tech Enthusiasts",
        teamLead: "Tummala Naveen",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "Screen warriors",
        teamLead: "Bodanapati Pavani",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "Achievers",
        teamLead: "Derengula sharath",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "03_Innovators",
        teamLead: "CHARAN KANJOJU",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "Sharoon",
        teamLead: "Sharan Teja Charagondla",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "Titans",
        teamLead: "LAISHETTY MANIKUMAR",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "Team Invincible",
        teamLead: "PEDAPALLI RAVI KIRAN",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "WebWonders",
        teamLead: "Sama Rashmika Reddy",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Victory Wipers",
        teamLead: "Sai Charan Suggala",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Codecharms",
        teamLead: "Dandewar.Sai manasa",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "KAVYA SREE",
    number: "15",
    teams: [
      {
        teamNumber: 1,
        teamName: "05_CodeCrafters",
        teamLead: "Moghekar Shivasai Kumar",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "01_Innovaters",
        teamLead: "Jella Ruchitanjani",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "Team Shiv",
        teamLead: "Kothapally Narayana Renu Rishik",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "Antharjal",
        teamLead: "Navaneeth Reddy Nalla",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "03_kanyarasi",
        teamLead: "KURAPATI VIVEK",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "Hacker Earth",
        teamLead: "T.Srenitha",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "WebWits",
        teamLead: "Meghana Vaddepally",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "Clash-Coders",
        teamLead: "K.Shreeja",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Team robin karp",
        teamLead: "Md Abdul Hadi",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "BLOCKCODERS",
        teamLead: "Vinay Mekala",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "N. N. S. L. Asritha",
    number: "16",
    teams: [
      {
        teamNumber: 1,
        teamName: "Incredibles",
        teamLead: "G.Madhumathi",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "GANAPATHI",
        teamLead: "GANESH BAIRI",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "02_Tech titans",
        teamLead: "Mittapally Sanjana",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "TechTroopers",
        teamLead: "Vivek Kumar Kashyap",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "DVS Hack Attackers",
        teamLead: "Drishika Mekonda",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "01_Smart coders",
        teamLead: "Y.Navadeep Reddy",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "WebMasters",
        teamLead: "GUVVA RAMASRI",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "V-5",
        teamLead: "Lanka Nitya",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Jahnavi",
        teamLead: "Gottam Jahnavi",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Skill issues",
        teamLead: "B.Shiva Shankar",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "N. N. S. L. Asritha",
    number: "16",
    teams: [
      {
        teamNumber: 1,
        teamName: "Incredibles",
        teamLead: "G.Madhumathi",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "GANAPATHI",
        teamLead: "GANESH BAIRI",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "02_Tech titans",
        teamLead: "Mittapally Sanjana",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "TechTroopers",
        teamLead: "Vivek Kumar Kashyap",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "DVS Hack Attackers",
        teamLead: "Drishika Mekonda",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "01_Smart coders",
        teamLead: "Y.Navadeep Reddy",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "WebMasters",
        teamLead: "GUVVA RAMASRI",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "V-5",
        teamLead: "Lanka Nitya",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Jahnavi",
        teamLead: "Gottam Jahnavi",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Skill issues",
        teamLead: "B.Shiva Shankar",
        timeSlot1: "4:00 - 4:15",
      },
    ],
  },
  {
    name: "B.ANIRUDH",
    number: "17",
    teams: [
      {
        teamNumber: 1,
        teamName: "Team_01",
        teamLead: "Dorepally Lohitha",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "Team_02",
        teamLead: "Palla Srihitha Reddy",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "Team_03",
        teamLead: "Srivardhan  Veeramalli",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "Team_04",
        teamLead: "G. Harsha Vardhan",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "Team_05",
        teamLead: "Ruttala Prawallika",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "Team_06",
        teamLead: "R. Rakesh",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "Team_07",
        teamLead: "Kandula Sai Dhakshitha",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "Team_08",
        teamLead: "Meghana Panyala",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Team_09",
        teamLead: "SWETHA MUTHYALA",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Team_10",
        teamLead: "Kesoju Sai priya",
        timeSlot1: "4:00 - 4:15",
      },
      {
        teamNumber: 11,
        teamName: "Team_11",
        teamLead: "Akhil",
        timeSlot1: "4:15 - 4:30",
      },
    ],
  },
  {
    name: "P. SAI DUSHYANTH",
    number: "18",
    teams: [
      {
        teamNumber: 1,
        teamName: "Team_12",
        teamLead: "Bhargav T",
        timeSlot1: "1:45 - 2:00",
      },
      {
        teamNumber: 2,
        teamName: "Team_13",
        teamLead: "Shaik Navrin",
        timeSlot1: "2:00 - 2:15",
      },
      {
        teamNumber: 3,
        teamName: "Team_14",
        teamLead: "Gella Sravani",
        timeSlot1: "2:15 - 2:30",
      },
      {
        teamNumber: 4,
        teamName: "Team_15",
        teamLead: "Bojja Manoj",
        timeSlot1: "2:30 - 2:45",
      },
      {
        teamNumber: 5,
        teamName: "Team_16",
        teamLead: "Sri varsha",
        timeSlot1: "2:45 - 3:00",
      },
      {
        teamNumber: 6,
        teamName: "Team_17",
        teamLead: "Varshita",
        timeSlot1: "3:00 - 3:15",
      },
      {
        teamNumber: 7,
        teamName: "Team_18",
        teamLead: "Tadepalli Thanmayee",
        timeSlot1: "3:15 - 3:30",
      },
      {
        teamNumber: 8,
        teamName: "Team_19",
        teamLead: "Sahithi Guddanti",
        timeSlot1: "3:30 - 3:45",
      },
      {
        teamNumber: 9,
        teamName: "Team_20",
        teamLead: "Harika danduprolu",
        timeSlot1: "3:45 - 4:00",
      },
      {
        teamNumber: 10,
        teamName: "Team_21",
        teamLead: "PATTEM GURU MAHESH",
        timeSlot1: "4:00 - 4:15",
      },
      {
        teamNumber: 11,
        teamName: "Team_22",
        teamLead: "Muthineni Akshara",
        timeSlot1: "4:15 - 4:30",
      },
    ],
  },
];

export default Teams;
